env:
  name: "simple_spread"      # MPE scenario name (e.g., simple_spread, simple_tag)
  max_episode_steps: 25
  num_agents: 3              # Number of agents in the environment

training:
  total_episodes: 2000
  max_steps_per_episode: 25
  batch_size: 1024
  gamma: 0.95
  tau: 0.01                 # Soft update parameter for target networks
  actor_lr: 0.001
  critic_lr: 0.001
  update_every: 100          # Steps between optimizer updates
  noise_std_dev: 0.2         # Standard deviation for noise process

replay_buffer:
  buffer_size: 1000000

logging:
  save_model_interval: 100    # Episodes between saving model checkpoints
  log_dir: "./results/logs"
  checkpoint_dir: "./results/checkpoints"

seed: 42
